version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

jobs:
  build:
    docker:
      - image: circleci/android:2024.04  # Gunakan versi spesifik
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-{{ checksum "build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: android-orb-v1-{{ checksum "build.gradle" }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Linting (Kotlin)
          command: ./gradlew ktlintCheck
      - run:
          name: Run Linting (Java)
          command: ./gradlew checkstyle
      - run:
          name: Run Vulnerability Check
          command: ./gradlew dependencyCheckAnalyze
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  build_and_test:
    jobs:
      - build
