version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Install Snyk
          command: |
            curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
            chmod +x snyk
            sudo mv snyk /usr/local/bin/
      - run:
          name: Run Snyk to Check for High Vulnerabilities
          command: snyk test --all-projects --severity-threshold=high
      - run:
          name: Run Snyk to Check for Medium Vulnerabilities
          command: snyk test --all-projects --severity-threshold=medium
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew test
#      - run:
#          name: Check Code Coverage
#          command: ./gradlew jacocoTestReport
#      - store_test_results:
#          path: app/build/test-results
#      - store_artifacts:
#          path: app/build/reports/jacoco
#          destination: jacoco
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
