version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile'
          executor: java17

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Install Maven Dependencies
          command: mvn clean install -U -X
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
